### ISSUE TITLE
support v7 of normalize-url

### ISSUE THREAD

**Issue by jlipps** [jaredwray/cacheable-request#106]
Version [7.0.1](https://github.com/sindresorhus/normalize-url/releases/tag/v7.0.1) of normalize-url saw a bugfix for use in Safari. My project only depends on normalize-url through intermediaries like Got and this project. I tried to apply a patch to this project to upgrade normalize-url to 7.0.1, but it appears as of v7 normalize-url is ESM-only. 

What's the stance of the maintainers here toward adjusting things to continue to rely on new versions of normalize-url, by supporting ESM imports?

**Comment by jaredwray** [comment]
@jlipps - thanks for the update and our goal is that over the next 90 days we will be upgrading all modules on this project to get it up to current. I am going to close this issue out and roll it into a bigger one.

**Comment by jlipps** [comment]
thanks for the heads up!

**Comment by jaredwray** [comment]
https://github.com/jaredwray/cacheable-request/pull/134
