### ISSUE TITLE
Make proper changelogs

### ISSUE THREAD

**Issue by sindresorhus** [jaredwray/cacheable-request#150]
https://github.com/jaredwray/cacheable-request/releases/tag/v8.0.0 is just a list of commits. 90% of the items there are not useful to users. A changelog should clearly document what the user-faceable changes are, especially what the breaking changes are in a major release.

Examples:
- https://github.com/sindresorhus/got/releases/tag/v12.0.0
- https://github.com/sindresorhus/eslint-plugin-unicorn/releases/tag/v43.0.0
- https://github.com/sindresorhus/boxen/releases/tag/v5.0.0

**Comment by jaredwray** [comment]
@sindresorhus - will do and thanks for the example. We are working on moving to pure ESM and will work on a better change log. Thanks for the examples.
