### ISSUE TITLE
Types needs to be updated for ESM

### ISSUE THREAD

**Issue by sindresorhus** [jaredwray/cacheable-request#171]
https://github.com/jaredwray/cacheable-request/blob/main/src/types.ts

You cannot use `namespace`. Use named exports instead of nesting in a namespace.

I don't have time to work on this, but if you mention me on a pull request, I'm happy to review it to ensure everything is correct.

**Comment by alphmth** [comment]
@jaredwray @sindresorhus can you review PR?

**Comment by jaredwray** [comment]
@alphmth and @sindresorhus - reviewed and merged.
