### ISSUE TITLE
[regression] Could not find a declaration file for module 'http-cache-semantics'

### ISSUE THREAD

**Issue by Maxim-Mazurok** [jaredwray/cacheable-request#218]
**Describe the bug**
Regression of https://github.com/jaredwray/cacheable-request/issues/194
It was previously fixed in https://github.com/jaredwray/cacheable-request/pull/195
And then broken again in https://github.com/jaredwray/cacheable-request/pull/217
Perhaps we need to add a test to prevent this in the future?

**How To Reproduce (best to provide workable code or tests!)**
See https://github.com/jaredwray/cacheable-request/issues/194

**Comment by jaredwray** [comment]
@Maxim-Mazurok are you getting this now? What is the code that I can validate off of as from my tests and validation it looks good.

**Comment by jaredwray** [comment]
Thanks for the pull request and merged + published as v10.2.5

**Comment by Maxim-Mazurok** [comment]
> @Maxim-Mazurok are you getting this now? What is the code that I can validate off of as from my tests and validation it looks good.

The reproduction is in #194 if you still need it:

> 1. `git clone -b create-pr-action/chore-npm-dedupe-0 https://github.com/Maxim-Mazurok/google-api-typings-generator`
> 2. `cd google-api-typings-generator`
> 3. optional `nvm i`
> 4. `npm ci`
> 5. Observe the error

---

> Thanks for the pull request and merged + published as v10.2.5

Thank you!
