### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by GalRab** [jaredwray/cacheable-request#222]
We have a memory leak when there is a lot of concurrency requests, the memory is raised until the container crashed.
It cause by this line:
`cachek.once('error', errorHandler);` // src/index.ts

I noticed there was a [commit (line 209)](https://github.com/jaredwray/cacheable-request/commit/5a9dae85d4a507908293b996e5cdc144083b741e#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80) that changed the behavior when the listener is removed.

Why did it change to remove the listener on error rather than on response?
Does the listener never remove if there is no error?

**Comment by jaredwray** [comment]
@GalRab - looking into this as I believe this was changed do to the way we are handling the response.

**Comment by GalRab** [comment]
> I created a new branch with a fix that would remove both. https://github.com/jaredwray/cacheable-request/tree/fixing-listener-memory-leak---issue-%23222
> 
> Can you validate that this resolves the issue?

yes, it seems to have resolve the issue

**Comment by jaredwray** [comment]
This has been released: https://github.com/jaredwray/cacheable-request/releases/tag/v10.2.6
