### ISSUE TITLE
7.0.3 Deployment now expects Node Version > 14, breaking change.

### ISSUE THREAD

**Issue by matt-fastpay** [jaredwray/cacheable-request#246]
**Describe the bug**
(node:30) UnhandledPromiseRejectionWarning: /src/node_modules/cacheable-request/dist/index.js:211
             cache.once?.('error', errorHandler);
                        ^
 
 SyntaxError: Unexpected token '.'
     at Module._compile (internal/modules/cjs/loader.js:892:18)
     at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
     at Module.load (internal/modules/cjs/loader.js:812:32)
     at Function.Module._load (internal/modules/cjs/loader.js:724:14)
     at Module.require (internal/modules/cjs/loader.js:849:19)
     at require (internal/modules/cjs/helpers.js:74:18)
     at Object.<anonymous> (/src/node_modules/got/dist/source/core/index.js:13:26)
     at Module._compile (internal/modules/cjs/loader.js:956:30)
     at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
     at Module.load (internal/modules/cjs/loader.js:812:32)

Use of optional chaining operator requires the service running the code to be Node v14 or higher. This was not a previous requirement of the 7.0.x deployments.

**How To Reproduce (best to provide workable code or tests!)**
Have a service running Node < 14
Reinstall node modules with 7.0.3 build
Start service, see failure.

**Comment by patricktyndall** [comment]
Seeing this as well. Is this the main repo for this project?

I don't see v7.0.3 on Github, only on npm.

**Comment by sirfuzzalot** [comment]
Potentially related error and affected downstream project - Serverless Framework (version 2.x.x). Getting this running a Serverless deploy on `Node v14.15.5`.

```
  Error: Cannot find module 'node:events'
  
  Require stack:
  - .../node_modules/got/node_modules/cacheable-request/dist/index.js
  - .../node_modules/got/dist/source/core/index.js
  - .../node_modules/got/dist/source/as-promise/types.js
  - .../node_modules/got/dist/source/as-promise/index.js
  - .../node_modules/got/dist/source/create.js
  - .../node_modules/got/dist/source/index.js
  - .../node_modules/serverless/lib/utils/eventuallyUpdate.js
  - .../node_modules/serverless/lib/Serverless.js
  - .../node_modules/serverless/scripts/serverless.js
  - .../node_modules/serverless/bin/serverless.js
  ```

**Comment by RoadRunner11** [comment]
Any idea if this has been fixed or when it will be fixed?

**Comment by otaviosilva22** [comment]
Isn't fixed yet. I hope it be fixed soon!

**Comment by sirfuzzalot** [comment]
> Seeing this as well. Is this the main repo for this project?
> 
> I don't see v7.0.3 on Github, only on npm.

I don't see a tag or release for v7.0.3 either, but the v7 branch does have 7.0.3 in the `package.json` file updated about 2 weeks ago by @jaredwray

**Comment by jaredwray** [comment]
fixing this now. Moving to a 7.0.4 as this was supposed to be a beta release.

**Comment by jaredwray** [comment]
@sirfuzzalot @otaviosilva22 @RoadRunner11 @patricktyndall can you validate that the `v7.0.4` release that we just pushed out resolves the issue. This was a bad merge and should not have happened.

**Comment by sirfuzzalot** [comment]
@jaredwray I'm getting successful deploys with Serverless Framework now on Node `14.15.5`. Appears to have fixed the issue. Thank you!

**Comment by otaviosilva22** [comment]
@jaredwray, i have success too. Thank you very much!
