### ISSUE TITLE
Instance is inaccessible

### ISSUE THREAD

**Issue by roneyrao** [jaredwray/cacheable-request#25]
Can you please refine the interface or add a new one to return the instance itself instead of a 'request' function. More control is needed in some cases.

**Comment by lukechilds** [comment]
Yes, sorry, that was a bad idea 😬.

So you wan't something like:

```js
const http = require('http');
const CacheableRequest = require('cacheable-request');
const cacheableRequest = new CacheableRequest(http.request);

cacheableRequest instanceof CacheableRequest;
// true

const cacheReq = cacheableRequest.request('http://example.com', cb);
cacheReq.on('request', req => req.end());
```

Out of interest, what is your use case?

**Comment by szmarczak** [comment]
@lukechilds has a good point. We need the Event Emitter in case the database is asynchronous.
