### ISSUE TITLE
Implementing RFC 5861: stale-while-revalidate and stale-if-error

### ISSUE THREAD

**Issue by sithmel** [jaredwray/cacheable-request#95]
Supporting method has been implemented on the http-cache-semantic library.

**Comment by jaredwray** [comment]
@sithmel - thanks for asking for this feature. Do you want to put together a pull request for us to review?

**Comment by jaredwray** [comment]
@sithmel - We have merged this into our `main` branch please verify that this is working as expected. Our plan is to release it in the next 10 days.
